chain_indent = "Block"
chain_split_single_child = true

closure_block_indent_threshold = 0

condense_wildcard_suffixes = true

fn_args_density = "CompressedIfEmpty"
fn_args_layout = "Visual"
fn_brace_style = "PreferSameLine"
fn_call_style = "Visual"
fn_return_indent = "WithWhereClause"
fn_single_line = true

generics_indent = "Visual"

hard_tabs = true

item_brace_style = "PreferSameLine"

reorder_imports = true
reorder_imported_names = true
reorder_imports_in_groups =	true

struct_lit_style = "Visual"

use_try_shorthand = true

wrap_comments = true
